apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: budget-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: budget-manager
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:15-alpine
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: budget_manager_pro
        - name: POSTGRES_USER
          value: budget_admin
        - name: POSTGRES_PASSWORD
          value: "CHANGE_ME"
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: budget-manager
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432